---
title: "chapter14-3-hypocotyl"
author: "Min-Yao"
date: "2020/3/19"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(rethinking)
hyp <- read.csv("hyp.lengths.both.experiments.labels.csv")
head(hyp)
summary(hyp)
str(hyp)
```

### 1. without pooling_base

```{r}
library(dplyr)
hyp_s <- sample_n(hyp, 1000)
summary(hyp_s)
str(hyp_s)


dat_list1 <- list(
  length = scale(hyp_s$length),
  line = as.integer(as.factor(hyp_s$line)),
  light = as.integer(hyp_s$light=="H")
)


modle_base <- ulam(
  alist(
    length ~ dnorm(mu, sigma),
    mu <- a[line] + bI[line]*light,
    a[line] ~ dnorm(0, 1),
    bI[line] ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ), data=dat_list1 , chains=4 , cores=4 , log_lik=TRUE)

precis( modle_base, depth=2 , pars=c("bI","sigma"))
plot( precis(modle_base) )
```

```{r}
library(tidyverse)
hyp_s_new <- hyp_s %>% unite("plate_exp", c("plate", "exp"), remove = FALSE)
#head(hyp_s_new)
str(hyp_s_new)

dat_list <- list(
  length = scale(hyp_s_new$length),
  line = as.integer(as.factor(hyp_s_new$line)),
  light = as.integer(hyp_s_new$light=="H"),
  plate_exp = as.integer(as.factor(hyp_s_new$plate_exp))
)

#head(dat_list)
summary(dat_list)
str(dat_list)
```

### 1.without pooling_fixed

```{r}
modle_fixed <- ulam(
  alist(
    length ~ dnorm(mu, sigma),
    mu <- a[line] + bI[line]*light + bP[plate_exp],
    a[line] ~ dnorm(0, 1),
    bI[line] ~ dnorm(0, 1),
    bP[plate_exp] ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ), data=dat_list , chains=4 , cores=4 , log_lik=TRUE)

precis( modle_fixed, depth=2 , pars=c("bI","sigma"))
plot( precis(modle_fixed) )
```

### 2.partial pooling across plate_exp

```{r}
modle_multilevel <- ulam(
  alist(
    length ~ dnorm(mu, sigma),
    mu <- a[line] + bI[line]*light + bP[plate_exp],
    a[line] ~ dnorm(a_bar, sigma_a),
    bI[line] ~ dnorm(0, 1),
    bP[plate_exp] ~ dnorm(0, sigma_p),
    a_bar ~ dnorm( 0 , 1 ),
    sigma_a ~ dexp(1),
    sigma_p ~ dexp(1),
    sigma ~ dexp(1)
  ), data=dat_list , chains=4 , cores=4 , log_lik=TRUE)

precis( modle_multilevel, depth=2 , pars=c("bI","sigma"))
plot(precis( modle_multilevel ))
```

```{r}
compare(modle_base, modle_fixed, modle_multilevel)
plot(compare(modle_base, modle_fixed, modle_multilevel))
```

### 3.As 2, but use a multivariate normal model for the line slope and intercept effects

```{r}
modle_base_multivariate <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- a[line] + bI[line]*light,
        c(a,bI)[line] ~ multi_normal( c(a_bar,b_bar) , Rho , sigma_line ),
        a_bar ~ normal(0,1),
        b_bar ~ normal(0,1),
        sigma_line ~ exponential(1),
        sigma ~ exponential(1),
        Rho ~ lkj_corr(2)
    ) , data=dat_list1 , chains=4 , cores=4, log_lik = TRUE )

precis(modle_base_multivariate, depth=3 , pars=c("Rho","sigma_line"))
```

```{r}
compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate)
plot(compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate))
```

```{r}
modle_fixed_multivariate <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- a[line] + bI[line]*light + bP[plate_exp],
        c(a,bI)[line] ~ multi_normal( c(a_bar,b_bar) , Rho , sigma_line ),
        a_bar ~ normal(0,1),
        b_bar ~ normal(0,1),
        bP[plate_exp] ~ dnorm(0, 1),
        sigma_line ~ exponential(1),
        sigma ~ exponential(1),
        Rho ~ lkj_corr(2)
    ) , data=dat_list , chains=4 , cores=4, log_lik = TRUE )

precis(modle_fixed_multivariate, depth=3 , pars=c("Rho","sigma_line"))
```

```{r}
compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate)
plot(compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate))
```

### multivariate normal model with varying slopes model

```{r}
dat_list2 <- list(
  length = scale(hyp_s$length),
  line = as.integer(as.factor(hyp_s$line)),
  light = ifelse(hyp_s$light=="H", 1L , 2L )
)
str(dat_list2)

modle_base_multivariate_vslope <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- g[light] + alpha[line,light],

        # adaptive priors
        vector[2]:alpha[line] ~ multi_normal(0,Rho_line,sigma_line),

        # fixed priors
        g[light] ~ dnorm(0,1),
        sigma_line ~ dexp(1),
        Rho_line ~ dlkjcorr(4),
        sigma ~ dexp(1)
    ), data=dat_list2 , chains=4 , cores=4 , log_lik = TRUE)

precis(modle_base_multivariate_vslope, depth=3 , pars=c("Rho_line","sigma_line"))
```

```{r}
dat_list3 <- list(
  length = scale(hyp_s_new$length),
  line = as.integer(as.factor(hyp_s_new$line)),
  light = ifelse(hyp_s$light=="H", 1L , 2L ),
  plate_exp = as.integer(as.factor(hyp_s_new$plate_exp))
)
summary(dat_list3)

modle_fixed_multivariate_vslope <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- g[light] + alpha[line,light] + beta[plate_exp,light],

        # adaptive priors
        vector[2]:alpha[line] ~ multi_normal(0,Rho_line,sigma_line),
        vector[2]:beta[plate_exp] ~ multi_normal(0,Rho_plate_exp,sigma_plate_exp),

        # fixed priors
        g[light] ~ dnorm(0,1),
        sigma_line ~ dexp(1),
        Rho_line ~ dlkjcorr(4),
        sigma_plate_exp ~ dexp(1),
        Rho_plate_exp ~ dlkjcorr(4),
        sigma ~ dexp(1)
    ) , data=dat_list3 , chains=4 , cores=4 , log_lik = TRUE)

precis(modle_fixed_multivariate_vslope, depth=3 , pars=c("Rho_line","sigma_line"))
```

```{r}
compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate,modle_base_multivariate_vslope,modle_fixed_multivariate_vslope)
plot(compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate,modle_base_multivariate_vslope,modle_fixed_multivariate_vslope))
```

### non-centered multivariate normal model with varying slopes model
```{r}
## R code 14.19
modle_base_multivariate_vslope_nc <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- g[light] + alpha[line,light],

        # adaptive priors - non-centered
        transpars> matrix[line,2]:alpha <-
                compose_noncentered( sigma_line , L_Rho_line , z_line ),
        
        matrix[2,line]:z_line ~ normal( 0 , 1 ),
        
        # fixed priors
        g[light] ~ normal(0,1),
        vector[2]:sigma_line ~ dexp(1),
        cholesky_factor_corr[2]:L_Rho_line ~ lkj_corr_cholesky( 2 ),
        sigma ~ dexp(1),

        # compute ordinary correlation matrixes from Cholesky factors
        gq> matrix[2,2]:Rho_line <<- multiply_lower_tri_self_transpose(L_Rho_line)
    ) , data=dat_list2 , chains=4 , cores=4 , log_lik=TRUE )

precis(modle_base_multivariate_vslope_nc, depth=3 , pars=c("Rho_line","sigma_line"))
```


```{r}
## R code 14.19
modle_fixed_multivariate_vslope_nc <- ulam(
    alist(
        length ~ normal(mu, sigma),
        mu <- g[light] + alpha[line,light] + beta[plate_exp,light],

        # adaptive priors - non-centered
        transpars> matrix[line,2]:alpha <-
                compose_noncentered( sigma_line , L_Rho_line , z_line ),
        transpars> matrix[plate_exp,2]:beta <-
                compose_noncentered( sigma_plate_exp , L_Rho_plate_exp , z_plate_exp ),
        matrix[2,line]:z_line ~ normal( 0 , 1 ),
        matrix[2,plate_exp]:z_plate_exp ~ normal( 0 , 1 ),

        # fixed priors
        g[light] ~ normal(0,1),
        vector[2]:sigma_line ~ dexp(1),
        cholesky_factor_corr[2]:L_Rho_line ~ lkj_corr_cholesky( 2 ),
        vector[2]:sigma_plate_exp ~ dexp(1),
        cholesky_factor_corr[2]:L_Rho_plate_exp ~ lkj_corr_cholesky( 2 ),
        sigma ~ dexp(1),

        # compute ordinary correlation matrixes from Cholesky factors
        gq> matrix[2,2]:Rho_line <<- multiply_lower_tri_self_transpose(L_Rho_line),
        gq> matrix[2,2]:Rho_plate_exp <<- multiply_lower_tri_self_transpose(L_Rho_plate_exp)
    ) , data=dat_list3 , chains=4 , cores=4 , log_lik=TRUE )

precis(modle_fixed_multivariate_vslope_nc, depth=3 , pars=c("Rho_line","sigma_line"))
```

```{r}
compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate,modle_base_multivariate_vslope,modle_fixed_multivariate_vslope,modle_base_multivariate_vslope_nc,modle_fixed_multivariate_vslope_nc)
plot(compare(modle_base, modle_fixed, modle_multilevel,modle_base_multivariate,modle_fixed_multivariate,modle_base_multivariate_vslope,modle_fixed_multivariate_vslope,modle_base_multivariate_vslope_nc,modle_fixed_multivariate_vslope_nc))
```

