---
title: "chapter14-3"
author: "Min-Yao"
date: "2020/3/19"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(rethinking)
library(foreign)
qob = read.dta("NEW7080.dta")
head(qob)
```

```{r}
library(tidyverse)
library(dplyr)
qob <- as_tibble(qob)
head(qob)
qob_new = qob %>% 
  rename(
    AGE = v1,
    AGEQ = v2,
    EDUC = v4,
    ENOCENT = v5,
    ESOCENT = v6,
    LWKLYWGE = v9,
    MARRIED = v10,
    MIDATL = v11,
    MT = v12,
    NEWENG = v13,
    CENSUS = v16,
    QOB = v18,
    RACE = v19,
    SMSA = v20,
    SOATL = v21,
    WNOCENT = v24,
    WSOCENT = v25,
    YOB = v27
    )
head(qob_new)
summary(qob_new)
str(qob_new)

qob_new2 <- sample_n(qob_new, 10000)
summary(qob_new2)
str(qob_new2)
```

```{r}
dat <- list(
    W=standardize(qob_new2$LWKLYWGE) ,
    E=standardize(qob_new2$EDUC) ,
    Q=standardize(qob_new2$QOB) )
summary(dat)
str(dat)
```

```{r}
## R code 14.24
m14.4_qob <- ulam(
    alist(
        W ~ dnorm( mu , sigma ),
        mu <- aW + bEW*E,
        aW ~ dnorm( 0 , 0.2 ),
        bEW ~ dnorm( 0 , 0.5 ),
        sigma ~ dexp( 1 )
    ) , data=dat , chains=4 , cores=4 , log_lik = TRUE)

precis( m14.4_qob )
```

```{r}
## R code 14.25
m14.5_qob <- ulam(
    alist(
        c(W,E) ~ multi_normal( c(muW,muE) , Rho , Sigma ),
        muW <- aW + bEW*E,
        muE <- aE + bQE*Q,
        c(aW,aE) ~ normal( 0 , 0.2 ),
        c(bEW,bQE) ~ normal( 0 , 0.5 ),
        Rho ~ lkj_corr( 2 ),
        Sigma ~ exponential( 1 )
    ), data=dat , chains=4 , cores=4 )

precis( m14.5_qob , depth=3 )
```



