---
title: "R Notebook"
output: html_notebook
---

### Installation of RStan
```{r}
remove.packages("rstan")
if (file.exists(".RData")) file.remove(".RData")
```

```{r}
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
```


### Checking the C++ Toolchain
```{r}
pkgbuild::has_build_tools(debug = TRUE)
```


### Configuration of the C++ Toolchain
```{r}
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))
if (!file.exists(M)) file.create(M)
cat("\nCXX14FLAGS=-O3 -march=native -mtune=native",
    if( grepl("^darwin", R.version$os)) "CXX14FLAGS += -arch x86_64 -ftemplate-depth-256" else 
    if (.Platform$OS.type == "windows") "CXX11FLAGS=-O3 -march=native -mtune=native" else
    "CXX14FLAGS += -fPIC",
    file = M, sep = "\n", append = TRUE)
```

### How to Use RStan

```{r}
library("rstan") # observe startup messages
```

```{r}
options(mc.cores = parallel::detectCores())
```

```{r}
rstan_options(auto_write = TRUE)
```

```{r}
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```



```{r}
install.packages(c("devtools","mvtnorm","loo","coda"),dependencies=TRUE)
library(devtools)
install_github("rmcelreath/rethinking",ref="Experimental")
```

```{r}

install.packages("brms")
```

```{r}
install.packages("tidyverse")
```

## How to Use RStan

### Loading the package
```{r}
library("rstan") # observe startup messages
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```


### Example 1: Eight Schools
```{r}
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
```


```{r}
fit <- stan(file = '8schools.stan', data = schools_dat)
```

```{r}
print(fit)
plot(fit)
pairs(fit, pars = c("mu", "tau", "lp__"))

la <- extract(fit, permuted = TRUE) # return a list of arrays 
mu <- la$mu 

### return an array of three dimensions: iterations, chains, parameters 
a <- extract(fit, permuted = FALSE) 

### use S3 functions on stanfit objects
a2 <- as.array(fit)
m <- as.matrix(fit)
d <- as.data.frame(fit)
```

